### ISSUE TITLE
Tight spacing for segmented control

### ISSUE THREAD

**Issue by jkeussen** [bmarkowitz/breakaway-info#1]
Steps to reproduce:

1. Go to Stats or Discover tab
2. Tap on a Player
3. Scroll down to Stats section and tap "See all"
4. Segmented control at the top is touching the navigation bar and have no top spacing.

![image](https://user-images.githubusercontent.com/1137557/131478834-342f4a70-3334-41ee-bc84-c153f5252bc9.png)

Maybe a tall header with segmented controls built-in would be nice here?

**Comment by bmarkowitz** [comment]
Thanks for this.. it will be fixed in beta 2. 👍
