### ISSUE TITLE
Strange indentation/spacing on shootout info

### ISSUE THREAD

**Issue by ghost** [bmarkowitz/breakaway-info#2]
Steps to reproduce:
1. Go to game with a shootout. (VAN vs EDM on Oct 13, 2021)
2. Scroll down to the shootout section.
3. The names don't seem to be aligned consistently or in a way that makes sense.

I'm on iPhone 7 Plus w/ iOS 14.8

![IMG_3290](https://user-images.githubusercontent.com/19616035/137327502-d2f97031-a7f9-43b3-877e-a64cb0f42091.PNG)

**Comment by bmarkowitz** [comment]
Noted. Thank you @kangzhiz!
